(()=>{
if(location.pathname.replace(/\/+$/,'')!=='/timeclock')return;
const URL='https://eomgnaulupqiwjzcimqt.supabase.co',KEY='sb_publishable_p20lJcecq2HN7trRTDMW8Q_iCYVnQsM',root=document.querySelector('#content');const show=(m,t='OnePoint',type='error')=>window.onePointMessage?window.onePointMessage(m,t,type):window.alert(m);let identified=null,clockTimer=null;
async function call(body){const r=await fetch(`${URL}/functions/v1/kiosk-access`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'Time Clock request failed.');return d}
function token(){return localStorage.getItem('onepoint_kiosk_token')||''}
function clockText(){const n=new Date();return{time:n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),date:n.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}}
function updateClock(){const t=clockText();const a=document.querySelector('#kTime'),b=document.querySelector('#kDate');if(a)a.textContent=t.time;if(b)b.textContent=t.date}
function noDevice(message='This browser has not been activated for a location.'){if(clockTimer)clearInterval(clockTimer);root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><h2>Device Activation Required</h2><p class="muted">${message}</p><a class="btn primary" href="/timeclock/activate/" style="display:block;text-align:center;margin-top:20px">Activate This Device</a></div></div>`}
async function start(){const t=token();if(!t)return noDevice();try{const d=await call({action:'device_status',device_token:t});renderClock(d.store)}catch(e){localStorage.removeItem('onepoint_kiosk_token');localStorage.removeItem('onepoint_kiosk_store');noDevice(e.message)}}
function renderClock(store){identified=null;if(clockTimer)clearInterval(clockTimer);const t=clockText();root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><div class="time" id="kTime">${t.time}</div><div class="date" id="kDate">${t.date}</div><div class="notice" style="margin-top:18px"><b>${store?.name||store?.store_code||'Location'}</b>${store?.store_code?` · ${store.store_code}`:''}</div><div class="field section"><label>Employee ID</label><input id="kEmployee" inputmode="numeric" autocomplete="off" style="height:66px;font-size:22px;text-align:center"></div><div class="field"><label>PIN</label><input id="kPin" type="password" inputmode="numeric" autocomplete="off" maxlength="8" style="height:66px;font-size:22px;text-align:center"></div><button class="btn primary" id="kContinue" style="width:100%;height:70px;margin-top:16px;font-size:18px">Continue</button><div id="kEmployeeState" class="section"></div><a href="/timeclock/activate/" class="muted" style="display:inline-block;margin-top:20px;font-size:12px">Device setup</a></div></div>`;clockTimer=setInterval(updateClock,1000);document.querySelector('#kContinue').onclick=identify;document.querySelector('#kEmployee').focus()}
async function identify(){const employee_number=document.querySelector('#kEmployee').value.trim(),pin=document.querySelector('#kPin').value.trim(),b=document.querySelector('#kContinue'),old=b.textContent;b.disabled=true;b.textContent='Checking…';try{const d=await call({action:'identify',device_token:token(),employee_number,pin});identified={employee_number,pin,...d};const box=document.querySelector('#kEmployeeState');if(!d.same_store){box.innerHTML=`<div class="notice"><b>${d.employee.name}</b><div class="muted">Currently clocked in at another location.</div></div>`;return}const action=d.next_action==='clock_out'?'Clock Out':'Clock In';box.innerHTML=`<div class="card" style="margin-top:14px;text-align:left"><h3 style="margin-top:0">${d.employee.name}</h3>${d.recent_clock_in?`<div class="muted">Recent clock-in: ${new Date(d.recent_clock_in).toLocaleString()}</div>`:''}<button class="btn primary" id="kPunch" style="width:100%;height:64px;margin-top:14px">${action}</button></div>`;document.querySelector('#kPunch').onclick=punch}catch(e){show(e.message||String(e),'Time Clock')}finally{b.disabled=false;b.textContent=old}}
async function punch(){if(!identified)return;const b=document.querySelector('#kPunch'),old=b.textContent;b.disabled=true;b.textContent='Recording…';try{const d=await call({action:'punch',device_token:token(),employee_number:identified.employee_number,pin:identified.pin});if(clockTimer)clearInterval(clockTimer);root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><div style="font-size:64px;margin:20px 0">✓</div><h2>${d.action==='clock_in'?'Clocked In':'Clocked Out'}</h2><h3>${d.employee_name}</h3><div class="muted">${new Date(d.timestamp).toLocaleString()}</div>${d.warning?`<div class="notice" style="margin-top:18px">${d.warning}</div>`:''}<div class="muted section">Returning to login…</div></div></div>`;setTimeout(()=>start(),2600)}catch(e){show(e.message||String(e),'Time Clock');b.disabled=false;b.textContent=old}}
setTimeout(start,350);
})();