(()=>{
if(location.pathname.replace(/\/+$/,'')!=='/timeclock')return;
const URL='https://eomgnaulupqiwjzcimqt.supabase.co',KEY='sb_publishable_p20lJcecq2HN7trRTDMW8Q_iCYVnQsM',root=document.querySelector('#content');
const show=(m,t='Time Clock',type='error')=>window.onePointMessage?window.onePointMessage(m,t,type):window.alert(m);let clockTimer=null;
const style=document.createElement('style');style.textContent=`.clockWrap{min-height:calc(100vh - 120px);display:grid;place-items:center}.clock{width:min(520px,94vw);text-align:center;margin:auto}.clock .brandline{font-size:17px;font-weight:800;letter-spacing:.13em}.kStore{font-size:30px;font-weight:800;margin:10px 0 24px}.clock .time{font-size:68px;font-weight:800;line-height:1;width:100%}.clock .date{font-size:28px;font-weight:700;margin:12px auto 32px;width:100%;line-height:1.2}.kFields{display:grid;gap:22px}.kFields .field{text-align:left}.kFields label{font-size:18px;font-weight:700;display:block;margin-bottom:8px}.kFields input{height:72px;font-size:28px;text-align:center;font-weight:700;letter-spacing:.04em}.kPunches{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}.kPunches .btn{height:74px;font-size:20px;font-weight:800}.kSetupDisabled{border:0;background:none;color:#9ca3af;margin-top:24px;font-size:12px;cursor:default}@media(max-width:560px){.clock .time{font-size:56px}.clock .date{font-size:23px}.kStore{font-size:25px}.kPunches{gap:10px}}`;document.head.appendChild(style);
async function call(body){const r=await fetch(`${URL}/functions/v1/kiosk-access`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.error){const e=new Error(d.error||'Time Clock request failed.');e.data=d;throw e}return d}
function token(){return localStorage.getItem('onepoint_kiosk_token')||''}
function clockText(){const n=new Date();return{time:n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),date:n.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'})}}
function updateClock(){const t=clockText(),a=document.querySelector('#kTime'),b=document.querySelector('#kDate');if(a)a.textContent=t.time;if(b)b.textContent=t.date}
function noDevice(message='Store onboard needed.'){if(clockTimer)clearInterval(clockTimer);root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><h2 style="font-size:32px;margin-top:24px">Store onboard needed.</h2><p class="muted">${message}</p><a class="btn primary" href="/timeclock/activate/" style="display:block;text-align:center;margin-top:22px;height:60px;line-height:42px">Onboard / Activate Store</a></div></div>`}
async function start(){const t=token();if(!t)return noDevice();try{const d=await call({action:'device_status',device_token:t});renderClock(d.store)}catch(e){localStorage.removeItem('onepoint_kiosk_token');localStorage.removeItem('onepoint_kiosk_store');noDevice(e.message||'Store onboard needed.')}}
function renderClock(store){if(clockTimer)clearInterval(clockTimer);const t=clockText(),storeName=store?.name||'Location';root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><div class="kStore">${storeName}</div><div class="time" id="kTime">${t.time}</div><div class="date" id="kDate">${t.date}</div><div class="kFields"><div class="field"><label>Employee ID</label><input id="kEmployee" inputmode="numeric" autocomplete="off"></div><div class="field"><label>PIN</label><input id="kPin" type="password" inputmode="numeric" autocomplete="off" maxlength="8"></div></div><div class="kPunches"><button class="btn primary" id="kClockIn">Clock In</button><button class="btn secondary" id="kClockOut">Clock Out</button></div><button type="button" class="kSetupDisabled" id="kSetupDisabled" aria-disabled="true">Device setup</button></div></div>`;clockTimer=setInterval(updateClock,1000);document.querySelector('#kClockIn').onclick=()=>punch('clock_in');document.querySelector('#kClockOut').onclick=()=>punch('clock_out');document.querySelector('#kSetupDisabled').onclick=e=>e.preventDefault();document.querySelector('#kEmployee').focus()}
async function punch(requested_action){const employee_number=document.querySelector('#kEmployee')?.value.trim()||'',pin=document.querySelector('#kPin')?.value.trim()||'',buttons=[document.querySelector('#kClockIn'),document.querySelector('#kClockOut')].filter(Boolean),clicked=requested_action==='clock_in'?document.querySelector('#kClockIn'):document.querySelector('#kClockOut');const old=clicked?.textContent;buttons.forEach(b=>b.disabled=true);if(clicked)clicked.textContent='Recording…';try{const d=await call({action:'punch',requested_action,device_token:token(),employee_number,pin});if(clockTimer)clearInterval(clockTimer);root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="brandline">ONEPOINT TIME CLOCK</div><div style="font-size:72px;margin:22px 0">✓</div><h2 style="font-size:34px">${d.action==='clock_in'?'Clocked In':'Clocked Out'}</h2><h3 style="font-size:25px">${d.employee_name}</h3><div class="muted" style="font-size:18px">Employee ID: ${employee_number}</div><div class="muted" style="font-size:18px;margin-top:8px">${new Date(d.timestamp).toLocaleString()}</div>${d.warning?`<div class="notice" style="margin-top:20px">${d.warning}</div>`:''}<div class="muted section">Returning to clock…</div></div></div>`;setTimeout(()=>start(),2600)}catch(e){show(e.message||String(e),'Time Clock','error')}finally{buttons.forEach(b=>b.disabled=false);if(clicked&&old)clicked.textContent=old}}
setTimeout(start,250);
})();