(()=>{
const path=location.pathname.replace(/\/+$/,'')||'/';if(path!=='/timeclock'&&!(location.hostname==='cashier.onepointsystems.io'&&path==='/'))return;
const URL='https://eomgnaulupqiwjzcimqt.supabase.co',KEY='sb_publishable_p20lJcecq2HN7trRTDMW8Q_iCYVnQsM',root=document.querySelector('#content');
const show=(m,t='Time Clock',type='error')=>window.onePointMessage?window.onePointMessage(m,t,type):window.alert(m);let clockTimer=null;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const style=document.createElement('style');style.textContent=`
body.opClockNoSide .clockWrap{min-height:calc(100vh - 54px);display:grid;place-items:center;padding:18px 0}
body.opClockNoSide .clock{width:min(620px,94vw);text-align:center;margin:auto;position:relative;padding-bottom:24px}
.kHero{display:grid;place-items:center;gap:7px;margin:0 auto 22px;padding:18px 20px;border:1px solid color-mix(in srgb,var(--op-accent,#0071e3) 15%,transparent);border-radius:20px;background:var(--op-accent-soft,#e8f1fb)}
.kLogoMount{display:grid;place-items:center;min-height:72px;width:100%}.kLogoMount .opBrandLogo{width:min(280px,72vw);height:84px;object-fit:contain;margin:0 auto;border-radius:12px}.kLogoFallback{width:58px;height:58px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(145deg,var(--op-accent,#0071e3),#58a6ff);color:#fff;font-size:28px;font-weight:800;box-shadow:0 8px 20px rgba(0,113,227,.18)}
.kStore{font-size:30px;font-weight:780;letter-spacing:-.035em;line-height:1.08;margin:2px 0 0;max-width:100%;text-wrap:balance}
.kTrusted{display:inline-flex;align-items:center;justify-content:center;gap:6px;margin:0 auto 18px;padding:5px 10px;border-radius:999px;background:#ecfdf3;color:#166534;font-size:12px;font-weight:700}
.clock .time{font-size:68px;font-weight:780;line-height:1;width:100%;letter-spacing:-.055em}.clock .date{font-size:24px;font-weight:650;margin:12px auto 28px;width:100%;line-height:1.2;color:var(--pup-secondary,#6e6e73)}
.kFields{display:grid;gap:18px;max-width:420px;margin:0 auto}.kFields .field{text-align:center;margin:0}.kFields label{font-size:15px;font-weight:700;display:block;margin-bottom:7px;text-align:center}.kFields input{height:64px;font-size:26px;text-align:center;font-weight:700;letter-spacing:.04em;margin:0 auto}
.kPunches{display:grid;grid-template-columns:1fr 1fr;gap:12px;max-width:420px;margin:22px auto 0}.kPunches .btn{height:64px;font-size:18px;font-weight:760;border-radius:13px}
.kClockFooter{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:22px 2px 0;padding-top:14px;border-top:1px solid var(--pup-line,rgba(60,60,67,.14));font-size:11px}.kFooterBrand{color:var(--pup-secondary,#6e6e73);font-weight:650;letter-spacing:.01em;text-align:left}.kSetupDisabled{border:0;background:none;color:var(--pup-tertiary,#86868b);font-size:11px;cursor:default;padding:4px 0;margin:0}.kSuccessMark{font-size:66px;line-height:1;margin:6px 0 18px}.kSuccessTitle{font-size:32px;margin:0}.kSuccessName{font-size:24px;margin:8px 0 0}.kSuccessMeta{font-size:16px;margin-top:7px}
@media(max-width:560px){body.opClockNoSide .clock{padding-left:18px;padding-right:18px}.clock .time{font-size:52px}.clock .date{font-size:20px}.kStore{font-size:25px}.kHero{padding:15px 14px}.kLogoMount .opBrandLogo{height:72px}.kPunches{gap:10px}.kPunches .btn{height:60px;font-size:17px}.kFields input{height:60px;font-size:24px}.kClockFooter{margin-top:18px}}
`;document.head.appendChild(style);
async function call(body){const fn=body?.action==='punch'?'shared-kiosk-punch':'kiosk-access',r=await fetch(`${URL}/functions/v1/${fn}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.error){const e=new Error(d.error||'Time Clock request failed.');e.data=d;throw e}return d}
async function deviceApi(body){const r=await fetch(`${URL}/functions/v1/kiosk-device-auth`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'Trusted device verification failed.');return d}
function token(){return localStorage.getItem('onepoint_kiosk_token')||''}
function markPosDevice(){try{document.cookie='onepoint_pos_device=1; Max-Age=31536000; Path=/; Domain=.onepointsystems.io; Secure; SameSite=Lax'}catch{}}
function clearHumanPortalSessions(){for(const k of ['onepoint-owner-auth','onepoint-manager-auth','onepoint-admin-auth']){try{sessionStorage.removeItem(k);localStorage.removeItem(k)}catch{}}}
function openKeyDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('onepoint-device-db',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('keys'))r.result.createObjectStore('keys',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getKeyRecord(){if(!window.indexedDB)return null;const db=await openKeyDb();return new Promise((resolve,reject)=>{const tx=db.transaction('keys','readonly'),r=tx.objectStore('keys').get('device-key');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function putKeyRecord(record){const db=await openKeyDb();return new Promise((resolve,reject)=>{const tx=db.transaction('keys','readwrite');tx.objectStore('keys').put(record);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
function toB64url(buf){const bytes=new Uint8Array(buf);let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function machineId(){let id=localStorage.getItem('onepoint_machine_id');if(id)return id;const rec=await getKeyRecord().catch(()=>null);if(rec?.machine_id){localStorage.setItem('onepoint_machine_id',rec.machine_id);return rec.machine_id}return''}
async function newDeviceKeyRecord(mid){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),publicJwk=await crypto.subtle.exportKey('jwk',pair.publicKey),pkcs8=await crypto.subtle.exportKey('pkcs8',pair.privateKey),privateKey=await crypto.subtle.importKey('pkcs8',pkcs8,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);return{id:'device-key',machine_id:mid,privateKey,publicJwk,created_at:new Date().toISOString()}}
async function ensureDeviceKey(deviceToken){if(!window.crypto?.subtle||!window.indexedDB||!deviceToken)return false;let mid=await machineId();if(!mid){mid=crypto.randomUUID();localStorage.setItem('onepoint_machine_id',mid)}let rec=await getKeyRecord().catch(()=>null);if(!rec||rec.machine_id!==mid||!rec.privateKey||!rec.publicJwk){rec=await newDeviceKeyRecord(mid);await putKeyRecord(rec)}await deviceApi({action:'register_key',device_token:deviceToken,machine_id:mid,public_key_jwk:rec.publicJwk});return true}
async function recoverWithDeviceKey(){if(!window.crypto?.subtle)return null;const rec=await getKeyRecord().catch(()=>null);if(!rec?.privateKey||!rec.machine_id)return null;localStorage.setItem('onepoint_machine_id',rec.machine_id);const c=await deviceApi({action:'challenge',machine_id:rec.machine_id}),sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},rec.privateKey,new TextEncoder().encode(c.challenge)),d=await deviceApi({action:'verify',machine_id:rec.machine_id,challenge_id:c.challenge_id,signature:toB64url(sig)});localStorage.setItem('onepoint_kiosk_token',d.device_token);localStorage.setItem('onepoint_kiosk_store',JSON.stringify(d.store||{}));markPosDevice();clearHumanPortalSessions();return d}
function clockText(){const n=new Date();return{time:n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),date:n.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'})}}
function updateClock(){const t=clockText(),a=document.querySelector('#kTime'),b=document.querySelector('#kDate');if(a)a.textContent=t.time;if(b)b.textContent=t.date}
function footer(){return`<div class="kClockFooter"><span class="kFooterBrand">OnePoint Time Clock</span><button type="button" class="kSetupDisabled" id="kSetupDisabled" aria-disabled="true">Device setup</button></div>`}
function hero(storeName,trusted=false){return`<div class="kHero"><div class="kLogoMount" aria-label="Business logo"></div><div class="kStore">${esc(storeName)}</div></div>${trusted?'<div class="kTrusted">✓ Trusted POS device</div>':''}`}
function noDevice(message='Store onboard needed.'){if(clockTimer)clearInterval(clockTimer);const activate=location.hostname==='cashier.onepointsystems.io'?'/activate':'/timeclock/activate/';root.innerHTML=`<div class="clockWrap"><div class="clock"><div class="kHero"><div class="kLogoMount"><div class="kLogoFallback">1</div></div><div class="kStore">OnePoint Time Clock</div></div><h2 style="font-size:30px;margin-top:20px;text-align:center">Store onboard needed.</h2><p class="muted" style="text-align:center">${esc(message)}</p><a class="btn primary" href="${activate}" style="display:block;text-align:center;margin:22px auto 0;max-width:360px;height:60px;line-height:42px">Onboard / Activate Store</a>${footer()}</div></div>`}
async function start(){let t=token();if(t){try{const d=await call({action:'device_status',device_token:t});markPosDevice();clearHumanPortalSessions();ensureDeviceKey(t).catch(()=>{});return renderClock(d.store,true)}catch{localStorage.removeItem('onepoint_kiosk_token')}}try{const d=await recoverWithDeviceKey();if(d)return renderClock(d.store,true)}catch(e){console.warn('Trusted device recovery:',e)}noDevice('This browser is not currently paired with a OnePoint location.')}
function renderClock(store,trusted=false){if(clockTimer)clearInterval(clockTimer);const t=clockText(),storeName=store?.name||store?.store_code||'Location';localStorage.setItem('onepoint_kiosk_store',JSON.stringify(store||{}));root.innerHTML=`<div class="clockWrap"><div class="clock">${hero(storeName,trusted)}<div class="time" id="kTime">${t.time}</div><div class="date" id="kDate">${t.date}</div><div class="kFields"><div class="field"><label for="kEmployee">Employee ID</label><input id="kEmployee" inputmode="numeric" autocomplete="off"></div><div class="field"><label for="kPin">PIN</label><input id="kPin" type="password" inputmode="numeric" autocomplete="off" maxlength="8"></div></div><div class="kPunches"><button class="btn clockInAction" id="kClockIn">Clock In</button><button class="btn clockOutAction" id="kClockOut">Clock Out</button></div>${footer()}</div></div>`;clockTimer=setInterval(updateClock,1000);document.querySelector('#kClockIn').onclick=()=>punch('clock_in');document.querySelector('#kClockOut').onclick=()=>punch('clock_out');document.querySelector('#kSetupDisabled').onclick=e=>e.preventDefault();document.querySelector('#kEmployee').focus();window.onePointRefreshClockBranding?.()}
async function punch(requested_action){const employee_number=document.querySelector('#kEmployee')?.value.trim()||'',pin=document.querySelector('#kPin')?.value.trim()||'',buttons=[document.querySelector('#kClockIn'),document.querySelector('#kClockOut')].filter(Boolean),clicked=requested_action==='clock_in'?document.querySelector('#kClockIn'):document.querySelector('#kClockOut');const old=clicked?.textContent;buttons.forEach(b=>b.disabled=true);if(clicked)clicked.textContent='Recording…';try{const d=await call({action:'punch',requested_action,device_token:token(),employee_number,pin}),stored=JSON.parse(localStorage.getItem('onepoint_kiosk_store')||'{}'),storeName=stored.name||stored.store_code||'Registered Location';if(clockTimer)clearInterval(clockTimer);root.innerHTML=`<div class="clockWrap"><div class="clock">${hero(storeName,true)}<div class="kSuccessMark">✓</div><h2 class="kSuccessTitle">${d.action==='clock_in'?'Clocked In':'Clocked Out'}</h2><h3 class="kSuccessName">${esc(d.employee_name)}</h3><div class="muted kSuccessMeta">Employee ID: ${esc(employee_number)}</div><div class="muted kSuccessMeta">${new Date(d.timestamp).toLocaleString()}</div>${d.warning?`<div class="notice" style="margin:20px auto 0;max-width:430px;text-align:center">${esc(d.warning)}</div>`:''}<div class="muted section" style="text-align:center">Returning to clock…</div>${footer()}</div></div>`;document.querySelector('#kSetupDisabled')?.addEventListener('click',e=>e.preventDefault());window.onePointRefreshClockBranding?.();setTimeout(()=>start(),2600)}catch(e){show(e.message||String(e),'Time Clock','error')}finally{buttons.forEach(b=>b.disabled=false);if(clicked&&old)clicked.textContent=old}}
setTimeout(start,250);
})();
