(()=>{
const URL='https://eomgnaulupqiwjzcimqt.supabase.co',KEY='sb_publishable_p20lJcecq2HN7trRTDMW8Q_iCYVnQsM';
const presets=new Set(['blue','emerald','violet','amber']);
const validHex=v=>/^#[0-9A-Fa-f]{6}$/.test(String(v||''));
function normalizePalette(p){if(!p||typeof p!=='object')return null;const out={accent:String(p.accent||''),hover:String(p.hover||''),soft:String(p.soft||''),text:String(p.text||'')};return Object.values(out).every(validHex)?out:null}
function clearCustom(){for(const k of ['--op-accent','--op-accent-hover','--op-accent-soft','--op-accent-text'])document.documentElement.style.removeProperty(k)}
function apply(v,palette=null){const custom=v==='custom'&&normalizePalette(palette);const theme=custom?'custom':presets.has(v)?v:'blue';document.documentElement.dataset.opTheme=theme;if(custom){document.documentElement.style.setProperty('--op-accent',custom.accent);document.documentElement.style.setProperty('--op-accent-hover',custom.hover);document.documentElement.style.setProperty('--op-accent-soft',custom.soft);document.documentElement.style.setProperty('--op-accent-text',custom.text)}else clearCustom();try{localStorage.setItem('onepoint_portal_theme',theme);if(custom)localStorage.setItem('onepoint_portal_palette',JSON.stringify(custom));else localStorage.removeItem('onepoint_portal_palette')}catch{};return theme}
try{const t=localStorage.getItem('onepoint_portal_theme')||'blue',p=JSON.parse(localStorage.getItem('onepoint_portal_palette')||'null');apply(t,p)}catch{apply('blue')}
async function fromPortal(){try{const sb=window.onePointSupabase||window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(!session)return;const{data:m}=await sb.from('organization_users').select('organization_id').eq('user_id',session.user.id).eq('active',true).in('role',['owner','manager']).maybeSingle();if(!m)return;const{data:o}=await sb.from('organizations').select('portal_theme,portal_theme_custom').eq('id',m.organization_id).maybeSingle();if(o?.portal_theme)apply(o.portal_theme,o.portal_theme_custom)}catch(e){console.warn('Theme:',e?.message||e)}}
async function fromKiosk(){try{const token=localStorage.getItem('onepoint_kiosk_token');if(!token)return;const r=await fetch(`${URL}/functions/v1/portal-theme-resolve`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({device_token:token})}),d=await r.json().catch(()=>({}));if(r.ok&&d.theme)apply(d.theme,d.palette)}catch(e){console.warn('Theme:',e?.message||e)}}
const p=location.pathname.replace(/\/+$/,'');if(p==='/owner'||p==='/manager'||p==='/timeclock/activate')setTimeout(fromPortal,250);if(p==='/timeclock'||p==='/timeclock/activate')setTimeout(fromKiosk,200);window.onePointApplyTheme=apply;
})();
