(()=>{
const path=location.pathname.replace(/\/+$/,'');if(path!=='/owner'&&path!=='/manager')return;
const SUPABASE_URL='https://eomgnaulupqiwjzcimqt.supabase.co',KEY='sb_publishable_p20lJcecq2HN7trRTDMW8Q_iCYVnQsM';const sb=window.onePointSupabase||window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const show=(m,t='OnePoint',type='error')=>window.onePointMessage?window.onePointMessage(m,t,type):window.alert(m);
const local=v=>{if(!v)return'';const d=new Date(v),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
function open(html){const d=$('#drawer'),b=$('#back');if(!d||!b)return;d.innerHTML=html;d.classList.add('modal');d.classList.remove('hidden');b.classList.remove('hidden')}
function close(){const d=$('#drawer'),b=$('#back');d?.classList.add('hidden');d?.classList.remove('modal');b?.classList.add('hidden')}
async function edit(id){try{const {data:e,error}=await sb.from('time_entries').select('id,organization_id,actual_clock_in,actual_clock_out,is_void,employees(name,employee_number),stores(name,store_code)').eq('id',id).maybeSingle();if(error)throw error;if(!e)throw new Error('Clock record not found.');if(e.is_void)throw new Error('Restore this record before editing it.');open(`<h2>Edit Clock Record</h2><p class="muted">${e.employees?.name||'Employee'} #${e.employees?.employee_number||''} · ${e.stores?.name||e.stores?.store_code||'Location'}</p><div class="field"><label>Clock In *</label><input id="teIn" type="datetime-local" value="${local(e.actual_clock_in)}"></div><div class="field"><label>Clock Out</label><input id="teOut" type="datetime-local" value="${local(e.actual_clock_out)}"></div><div class="field"><label>Correction Reason *</label><textarea id="teReason" rows="4" placeholder="Why is this clock record being corrected?"></textarea></div><p class="muted">Times are shown in this device's local timezone. DFW payable time is recalculated from the location operating hours.</p><div class="actions"><button class="btn primary" id="teSave">Save Correction</button><button class="btn secondary" id="teCancel">Cancel</button></div>`);$('#teCancel').onclick=close;$('#teSave').onclick=async()=>{const b=$('#teSave'),old=b.textContent,inVal=$('#teIn').value,outVal=$('#teOut').value,reason=$('#teReason').value.trim();if(!inVal)return show('Clock In is required.','Edit Clock Record');if(!reason)return show('Enter a correction reason.','Edit Clock Record');if(outVal&&new Date(outVal)<=new Date(inVal))return show('Clock Out must be after Clock In.','Edit Clock Record');b.disabled=true;b.textContent='Saving…';try{const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('Your session has expired. Sign in again.');const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-time-entry`,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({action:'edit_entry',entry_id:id,actual_clock_in:new Date(inVal).toISOString(),actual_clock_out:outVal?new Date(outVal).toISOString():null,reason})}),d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'Unable to save the correction.');close();show(d.warning?`Clock record corrected. ${d.warning}`:'Clock record corrected successfully.','Timesheet','success');setTimeout(()=>{if(path==='/owner'&&window.onePointOwnerPayroll?.render)window.onePointOwnerPayroll.render();else document.querySelector('#nav [data-tab="timesheets"]')?.click()},350)}catch(err){show(err.message||String(err),'Edit Clock Record')}finally{b.disabled=false;b.textContent=old}}}catch(err){show(err.message||String(err),'Edit Clock Record')}}
function inject(){for(const v of $$('.v2Void')){const id=v.dataset.id;if(v.parentElement?.querySelector(`.teEdit[data-id="${id}"]`))continue;const b=document.createElement('button');b.className='btn secondary teEdit';b.dataset.id=id;b.textContent='Edit';b.style.marginRight='6px';v.insertAdjacentElement('beforebegin',b);b.onclick=()=>edit(id)}}
document.addEventListener('click',e=>{if(e.target.closest('#nav [data-tab="timesheets"],#v2Apply,#v2Reset,.v2Sort,#v2History,.v2Restore'))setTimeout(inject,320)},false);setTimeout(inject,1000);window.onePointTimesheetEdit={edit};
})();