import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const isYmd=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v);

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
 const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return json({error:"Your session has expired. Sign in again."},401);
 const caller=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}}),admin=createClient(url,service,{auth:{persistSession:false}});
 const{data:{user},error:uErr}=await caller.auth.getUser();if(uErr||!user)return json({error:"Your session has expired. Sign in again."},401);
 let body:any;try{body=await req.json()}catch{return json({error:"Invalid request."},400)}
 const action=String(body.action||"");
 const isAdmin=async()=>{const{data}=await admin.from("platform_admins").select("user_id").eq("user_id",user.id).maybeSingle();return!!data};
 const businessOrg=async()=>{const{data,error}=await admin.from("organization_users").select("organization_id,role").eq("user_id",user.id).eq("active",true).in("role",["owner","manager"]).limit(1).maybeSingle();if(error)throw error;return data?.organization_id||null};
 async function businessAccess(orgId:string,storeId:string){const{data:store,error}=await admin.from("stores").select("id,organization_id,name,store_code,timezone,payroll_period,payroll_expected_hours,payroll_logic,active").eq("id",storeId).maybeSingle();if(error)throw error;if(!store||!store.active)return null;if(store.organization_id===orgId)return{store,owned:true};const{data:share,error:sErr}=await admin.from("store_shares").select("id").eq("store_id",storeId).eq("shared_organization_id",orgId).eq("active",true).maybeSingle();if(sErr)throw sErr;return share?{store,owned:false}:null}
 async function employeeAccess(orgId:string,employeeId:string){const{data:emp,error}=await admin.from("employees").select("id,organization_id,employee_number,name,status,base_pay_type,base_pay_rate").eq("id",employeeId).eq("status","active").maybeSingle();if(error)throw error;if(!emp)return null;if(emp.organization_id===orgId)return emp;const{data:share,error:sErr}=await admin.from("employee_org_shares").select("id").eq("employee_id",employeeId).eq("shared_organization_id",orgId).eq("active",true).maybeSingle();if(sErr)throw sErr;return share?emp:null}
 async function accessSnapshot(orgId:string){const{data:shares,error:shErr}=await admin.from("store_shares").select("id,store_id,owner_organization_id,shared_organization_id,active").eq("active",true).or(`owner_organization_id.eq.${orgId},shared_organization_id.eq.${orgId}`);if(shErr)throw shErr;const{data:owned,error:oErr}=await admin.from("stores").select("id,organization_id,name,store_code,timezone,payroll_period,payroll_expected_hours,payroll_logic,active").eq("organization_id",orgId).eq("active",true).order("store_code");if(oErr)throw oErr;const incomingIds=[...new Set((shares||[]).filter((x:any)=>x.shared_organization_id===orgId).map((x:any)=>x.store_id))];let incoming:any[]=[];if(incomingIds.length){const{data,error}=await admin.from("stores").select("id,organization_id,name,store_code,timezone,payroll_period,payroll_expected_hours,payroll_logic,active").in("id",incomingIds).eq("active",true).order("store_code");if(error)throw error;incoming=data||[]}const stores=[...(owned||[]),...incoming.filter((s:any)=>!(owned||[]).some((o:any)=>o.id===s.id))];return{shares:shares||[],owned:owned||[],incoming,stores}}
 async function ratesFor(orgId:string,ownedIds:string[],incomingIds:string[],employeeIds?:string[]){let ownedRates:any[]=[],sharedRates:any[]=[];if(ownedIds.length){let q=admin.from("employee_store_pay_rates").select("employee_id,store_id,pay_type,pay_rate,updated_at").in("store_id",ownedIds);if(employeeIds?.length)q=q.in("employee_id",employeeIds);const{data,error}=await q;if(error)throw error;ownedRates=(data||[]).map((r:any)=>({...r,organization_id:orgId,scope:"owned"}))}if(incomingIds.length){let q=admin.from("owner_store_pay_overrides").select("employee_id,store_id,pay_type,pay_rate,updated_at").eq("organization_id",orgId).in("store_id",incomingIds);if(employeeIds?.length)q=q.in("employee_id",employeeIds);const{data,error}=await q;if(error)throw error;sharedRates=(data||[]).map((r:any)=>({...r,organization_id:orgId,scope:"shared"}))}return[...ownedRates,...sharedRates]}
 try{
  if(action.startsWith("admin_")){
   if(!await isAdmin())return json({error:"Platform Admin access required."},403);
   if(action==="admin_store_options"){const storeId=String(body.store_id||""),{data:store,error:sErr}=await admin.from("stores").select("id,organization_id,name,store_code,active").eq("id",storeId).maybeSingle();if(sErr)throw sErr;if(!store)return json({error:"Location not found."},404);const{data:orgs,error:oErr}=await admin.from("organizations").select("id,name,status,organization_users(id,role,display_name,email,active)").neq("id",store.organization_id).order("name");if(oErr)throw oErr;const{data:shares,error:shErr}=await admin.from("store_shares").select("id,store_id,owner_organization_id,shared_organization_id,active,created_at").eq("store_id",storeId);if(shErr)throw shErr;const{data:assign}=await admin.from("employee_stores").select("employee_id").eq("store_id",storeId);const empIds=[...new Set((assign||[]).map((x:any)=>x.employee_id))];let employees:any[]=[];if(empIds.length){const{data}=await admin.from("employees").select("id,employee_number,name,status,organization_id").in("id",empIds).eq("status","active");employees=data||[]}return json({ok:true,store,organizations:(orgs||[]).map((o:any)=>({id:o.id,name:o.name,status:o.status,owner:(o.organization_users||[]).find((x:any)=>x.role==='owner'&&x.active)})),shares:shares||[],employees})}
   if(action==="admin_set_share"){const storeId=String(body.store_id||""),sharedOrg=String(body.shared_organization_id||"");if(!storeId||!sharedOrg)return json({error:"Choose a location and shared Owner."},400);const{data:store,error:sErr}=await admin.from("stores").select("id,organization_id,name,store_code").eq("id",storeId).maybeSingle();if(sErr)throw sErr;if(!store)return json({error:"Location not found."},404);if(store.organization_id===sharedOrg)return json({error:"Choose a different Owner organization."},400);const{error:upErr}=await admin.from("store_shares").upsert({store_id:storeId,owner_organization_id:store.organization_id,shared_organization_id:sharedOrg,active:true,created_by:user.id,updated_at:new Date().toISOString()},{onConflict:"store_id,shared_organization_id"});if(upErr)throw upErr;await admin.from("audit_logs").insert({organization_id:store.organization_id,actor_user_id:user.id,action:"store_shared_with_partner_owner",entity_type:"store",entity_id:store.id,details:{shared_organization_id:sharedOrg}});return json({ok:true})}
   if(action==="admin_remove_share"){const storeId=String(body.store_id||""),sharedOrg=String(body.shared_organization_id||""),{data:store}=await admin.from("stores").select("id,organization_id").eq("id",storeId).maybeSingle();if(!store)return json({error:"Location not found."},404);const{error}=await admin.from("store_shares").update({active:false,updated_at:new Date().toISOString()}).eq("store_id",storeId).eq("shared_organization_id",sharedOrg);if(error)throw error;const{count}=await admin.from("store_shares").select("id",{count:"exact",head:true}).eq("owner_organization_id",store.organization_id).eq("shared_organization_id",sharedOrg).eq("active",true);if(!count)await admin.from("employee_org_shares").update({active:false,updated_at:new Date().toISOString()}).eq("source_organization_id",store.organization_id).eq("shared_organization_id",sharedOrg);await admin.from("owner_store_pay_overrides").delete().eq("organization_id",sharedOrg).eq("store_id",storeId);await admin.from("audit_logs").insert({organization_id:store.organization_id,actor_user_id:user.id,action:"store_partner_share_removed",entity_type:"store",entity_id:store.id,details:{shared_organization_id:sharedOrg}});return json({ok:true})}
   return json({error:"Unsupported Admin action."},400);
  }
  const orgId=await businessOrg();if(!orgId)return json({error:"Owner or Manager access required."},403);
  if(action==="owner_snapshot"){
   const a=await accessSnapshot(orgId),sharedStoreIds=[...new Set(a.shares.map((x:any)=>x.store_id))];let sharedStores:any[]=[];if(sharedStoreIds.length){const{data,error}=await admin.from("stores").select("id,organization_id,name,store_code,timezone,payroll_period,payroll_expected_hours,payroll_logic,active").in("id",sharedStoreIds).eq("active",true);if(error)throw error;sharedStores=data||[]}
   let entries:any[]=[];if(sharedStoreIds.length){const{data,error}=await admin.from("time_entries").select("id,organization_id,employee_id,store_id,actual_clock_in,actual_clock_out,scheduled_open_at,scheduled_close_at,payable_clock_in,payable_clock_out,pay_type_snapshot,pay_rate_snapshot,is_void,missed_clock_out,early_clock_out,close_time_adjusted,system_closed_at").in("store_id",sharedStoreIds).eq("is_void",false).order("actual_clock_in",{ascending:false}).limit(5000);if(error)throw error;entries=data||[]}
   const{data:eos,error:eErr}=await admin.from("employee_org_shares").select("employee_id,source_organization_id,shared_organization_id,active").eq("shared_organization_id",orgId).eq("active",true);if(eErr)throw eErr;const empIds=[...new Set((eos||[]).map((x:any)=>x.employee_id))];let sharedEmployees:any[]=[];if(empIds.length){const{data,error}=await admin.from("employees").select("id,organization_id,employee_number,name,status,base_pay_type,base_pay_rate").in("id",empIds).eq("status","active");if(error)throw error;sharedEmployees=data||[]}
   const rates=await ratesFor(orgId,(a.owned||[]).map((s:any)=>s.id),a.incoming.map((s:any)=>s.id),empIds),orgIds=[...new Set([...(a.shares||[]).flatMap((x:any)=>[x.owner_organization_id,x.shared_organization_id]),...(eos||[]).map((x:any)=>x.source_organization_id)])];let orgs:any[]=[];if(orgIds.length){const{data}=await admin.from("organizations").select("id,name").in("id",orgIds);orgs=data||[]}
   return json({ok:true,organization_id:orgId,shares:a.shares,owned_stores:a.owned,shared_stores:sharedStores,entries,shared_employees:sharedEmployees,employee_shares:eos||[],store_pay_rates:rates,organizations:orgs});
  }
  if(action==="owner_payroll_snapshot"){
   const a=await accessSnapshot(orgId),storeIds=a.stores.map((s:any)=>s.id),ownedIds=a.owned.map((s:any)=>s.id),incomingIds=a.incoming.map((s:any)=>s.id),since=new Date(Date.now()-180*24*3600*1000).toISOString();let entries:any[]=[];if(storeIds.length){const{data,error}=await admin.from("time_entries").select("id,organization_id,employee_id,store_id,job_code_id,actual_clock_in,actual_clock_out,scheduled_open_at,scheduled_close_at,payable_clock_in,payable_clock_out,pay_type_snapshot,pay_rate_snapshot,is_void,missed_clock_out,early_clock_out,close_time_adjusted,system_closed_at").in("store_id",storeIds).eq("is_void",false).gte("actual_clock_in",since).order("actual_clock_in",{ascending:false}).limit(10000);if(error)throw error;entries=data||[]}
   const entryEmpIds=entries.map((x:any)=>x.employee_id),{data:ownEmp,error:oeErr}=await admin.from("employees").select("id,organization_id,employee_number,name,status,base_pay_type,base_pay_rate").eq("organization_id",orgId).eq("status","active");if(oeErr)throw oeErr;const{data:eos,error:eosErr}=await admin.from("employee_org_shares").select("employee_id,source_organization_id,shared_organization_id,active").eq("shared_organization_id",orgId).eq("active",true);if(eosErr)throw eosErr;const empIds=[...new Set([...(ownEmp||[]).map((x:any)=>x.id),...(eos||[]).map((x:any)=>x.employee_id),...entryEmpIds])];let employees:any[]=[];if(empIds.length){const{data,error}=await admin.from("employees").select("id,organization_id,employee_number,name,status,base_pay_type,base_pay_rate").in("id",empIds);if(error)throw error;employees=data||[]}
   const rates=await ratesFor(orgId,ownedIds,incomingIds,empIds),orgIds=[...new Set(a.shares.flatMap((x:any)=>[x.owner_organization_id,x.shared_organization_id]))];let orgs:any[]=[];if(orgIds.length){const{data}=await admin.from("organizations").select("id,name").in("id",orgIds);orgs=data||[]}
   return json({ok:true,organization_id:orgId,stores:a.stores,owned_store_ids:ownedIds,incoming_shared_store_ids:incomingIds,shares:a.shares,employees,entries,pay_rates:rates,organizations:orgs});
  }
  if(action==="owner_payroll_entries"){
   const start=String(body.start_date||""),end=String(body.end_date||"");if(!isYmd(start)||!isYmd(end)||start>end)return json({error:"Choose a valid payroll date range."},400);const a=await accessSnapshot(orgId),allowed=new Set(a.stores.map((s:any)=>s.id));let requested=Array.isArray(body.store_ids)?body.store_ids.map(String).filter((x:string)=>allowed.has(x)):[];if(!requested.length)requested=[...allowed];const employeeId=body.employee_id?String(body.employee_id):null;if(employeeId&&!await employeeAccess(orgId,employeeId))return json({error:"Employee access required."},403);const from=new Date(`${start}T00:00:00Z`);from.setUTCDate(from.getUTCDate()-1);const to=new Date(`${end}T23:59:59Z`);to.setUTCDate(to.getUTCDate()+1);let q=admin.from("time_entries").select("id,organization_id,employee_id,store_id,job_code_id,actual_clock_in,actual_clock_out,scheduled_open_at,scheduled_close_at,payable_clock_in,payable_clock_out,pay_type_snapshot,pay_rate_snapshot,is_void,missed_clock_out,early_clock_out,close_time_adjusted,system_closed_at").in("store_id",requested).gte("actual_clock_in",from.toISOString()).lte("actual_clock_in",to.toISOString()).order("actual_clock_in",{ascending:false}).limit(5000);if(employeeId)q=q.eq("employee_id",employeeId);const{data,error}=await q;if(error)throw error;const empIds=[...new Set((data||[]).map((x:any)=>x.employee_id))];let employees:any[]=[];if(empIds.length){const{data:er}=await admin.from("employees").select("id,organization_id,employee_number,name,status,base_pay_type,base_pay_rate").in("id",empIds);employees=er||[]}const ownedIds=requested.filter((id:string)=>a.owned.some((s:any)=>s.id===id)),incomingIds=requested.filter((id:string)=>a.incoming.some((s:any)=>s.id===id)),rates=await ratesFor(orgId,ownedIds,incomingIds,empIds);return json({ok:true,organization_id:orgId,stores:a.stores.filter((s:any)=>requested.includes(s.id)),employees,entries:data||[],pay_rates:rates});
  }
  if(action==="owner_set_store_pay"){
   const storeId=String(body.store_id||""),employeeId=String(body.employee_id||""),payType=body.pay_type==='hourly'||body.pay_type==='monthly'?body.pay_type:null,payRate=body.pay_rate==null||body.pay_rate===''?null:Number(body.pay_rate);if(!storeId||!employeeId||!payType||payRate==null||!Number.isFinite(payRate)||payRate<0)return json({error:"Choose a store, pay type, and valid pay amount."},400);const access=await businessAccess(orgId,storeId);if(!access)return json({error:"You do not have access to change pay for this location."},403);const emp=await employeeAccess(orgId,employeeId);if(!emp)return json({error:"This employee is not available to your organization."},403);if(access.owned){const{error}=await admin.from("employee_store_pay_rates").upsert({employee_id:employeeId,store_id:storeId,pay_type:payType,pay_rate:payRate,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"employee_id,store_id"});if(error)throw error}else{const{error}=await admin.from("owner_store_pay_overrides").upsert({organization_id:orgId,employee_id:employeeId,store_id:storeId,pay_type:payType,pay_rate:payRate,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"organization_id,employee_id,store_id"});if(error)throw error}await admin.from("audit_logs").insert({organization_id:orgId,actor_user_id:user.id,action:access.owned?"employee_store_pay_updated":"shared_store_owner_pay_override_updated",entity_type:"employee",entity_id:employeeId,details:{store_id:storeId,pay_type:payType,pay_rate:payRate,organization_override:!access.owned}});return json({ok:true,scope:access.owned?"owned":"shared_organization_override"});
  }
  if(action==="owner_clear_store_pay"){
   const storeId=String(body.store_id||""),employeeId=String(body.employee_id||""),access=await businessAccess(orgId,storeId);if(!access)return json({error:"You do not have access to this location."},403);if(access.owned){const{error}=await admin.from("employee_store_pay_rates").delete().eq("employee_id",employeeId).eq("store_id",storeId);if(error)throw error}else{const{error}=await admin.from("owner_store_pay_overrides").delete().eq("organization_id",orgId).eq("employee_id",employeeId).eq("store_id",storeId);if(error)throw error}await admin.from("audit_logs").insert({organization_id:orgId,actor_user_id:user.id,action:access.owned?"employee_store_pay_override_removed":"shared_store_owner_pay_override_removed",entity_type:"employee",entity_id:employeeId,details:{store_id:storeId,organization_override:!access.owned}});return json({ok:true});
  }
  return json({error:"Unsupported action."},400);
 }catch(e){console.error(e);return json({error:e instanceof Error?e.message:"Unexpected shared-store error"},500)}
});